### ISSUE TITLE
sugestão :)

### ISSUE THREAD

**Issue by isaacvicente** [andreza-vilar/Andreza-Vilar#1]
se vc quer mostrar o arquivo markdown no seu perfil, tem algumas coisas q tu precisa fazer:
- o nome do arquivo markdown precisa ser `README.md`
- nome desse repositório tem que bater com o seu nome de usuário, ou seja, `andreza-vilar`

espero ter ajudado

**Comment by andreza-vilar** [comment]
obrigada! ajudou muito, vou consertar esses erros :D
